### ISSUE TITLE
Meaningless Y labels for visual bars data 

### ISSUE THREAD

**Issue by jmkahn** [eberharf/cfl#1]
When I run create a CFL object and train it on the visual bars data, CFL returns labels for the y data, even though y labels are meaningless in this case (the Y in visual bars is a single binary variable). In the following code example, no error or warning is raised: 

`#partial code to reproduce issue: 
#(CDE and clusterer objects already created) 
#cfl core object 
cfl_object = tscfl.Two_Step_CFL_Core(condExp_object, cluster_object)
x_lbls, y_lbls = cfl_object.train(x, y)
`

This could be confusing or misleading for a user.

**Comment by iwahle** [comment]
No longer applicable, closing issue.
