### ISSUE TITLE
Below: find some assumptions that we implicitly make in the code that should be asserted 

### ISSUE THREAD

**Issue by jmkahn** [eberharf/cfl#15]
density estimation 
- Assume that the number of training epochs is an int > 0 

generate visual bars data 
- Assume that the noise level is a decimal between 0-1
- Assume that the random seed is an int 
- Assume that the im_shape is a tuple (int, int) 
- Assume that the number of images is an int >0

**Comment by iwahle** [comment]
TF should throw an error for # epochs. Visual bars assertions have been added.
