### ISSUE TITLE
Train vs Test -  Visual Bars dataset

### ISSUE THREAD

**Issue by nisha1729** [eberharf/cfl#23]
Hi, thanks for the repo! How do I ensure that the train and test data are truly separate?

**Comment by iwahle** [comment]
Hi, thanks for checking out the repo and for your question! Could you please clarify the question a bit - are you asking how to form train and test datasets using the `generate_visual_bars_data.py` script? In this case, you can first generate a single dataset using the script, and then randomly select a subset of those samples without replacement to withhold as a test set. Please let me know if this answers your questions or if you were asking about something else!

**Comment by nisha1729** [comment]
Thank you very much! Yes, that was my question.
